<a href="https://colab.research.google.com/github/vivek11416/tensorflow/blob/master/TF_hello_world.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import tensorflow as tf
print(tf.__version__)

c:\Users\vivek\anaconda3\lib\site-packages\scipy\__init__.py:146: UserWarning: A NumPy version >=1.16.5 and <1.23.0 is required for this version of SciPy (detected version 1.26.0
  warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion}"


2.14.0


In [6]:
#Create a tensor
scaler = tf.constant('Hello, Tensorflow !')
print(scaler)
print(scaler.numpy())
hello.ndim

tf.Tensor(b'Hello, Tensorflow !', shape=(), dtype=string)
b'Hello, Tensorflow !'


0

In [8]:
vector = tf.constant([[10,7],[7,10]])
print(vector.numpy())

[[10  7]
 [ 7 10]]


In [10]:
vector

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]])>

In [11]:
changable_tensor = tf.Variable([10,10])
unchangable_tensor = tf.constant([10,7])
changable_tensor,unchangable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10, 10])>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7])>)

In [13]:
changable_tensor[0].assign(7)

<tf.Variable 'UnreadVariable' shape=(2,) dtype=int32, numpy=array([ 7, 10])>

Scaler : a single number
Vector : a number with direction (e.g wind speed and direction)
Matrix :  a 2-d array of numbers
Tensor: an n dimentional array of numbers(where n can be any number , a 0-dimentional tensor is a scaler , a 1-d tensor is a vector)