<a href="https://colab.research.google.com/github/vivek11416/tensorflow/blob/master/TF_hello_world.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [10]:
import tensorflow as tf
print(tf.__version__)

2.10.1


In [11]:
scaler = tf.constant(7)
scaler

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [12]:
scaler.ndim

0

In [13]:
vector = tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10])>

In [14]:
vector.ndim

1

In [15]:
matrix  = tf.constant([[10,7],[7,10]])
matrix.ndim

2

In [16]:
tensor = tf.constant([[[1, 2, 3],
                       [4, 5, 6]],
                      [[7, 8, 9],
                       [10, 11, 12]],
                      [[13, 14, 15],
                       [16, 17, 18]]])
tensor.ndim

3

In [17]:
changable_tensor = tf.Variable([4,5])
non_changable_tensor = tf.constant([6,7])

In [18]:
changable_tensor[0].assign(8)
#non_changable_tensor[0].assign(8)

<tf.Variable 'UnreadVariable' shape=(2,) dtype=int32, numpy=array([8, 5])>

In [19]:
random_1 = tf.random.Generator.from_seed(42)
random_1 = random_1.normal(shape=(3,2))

random_2 = tf.random.Generator.from_seed(42)
random_2 = random_2.normal(shape=(3,2))

In [20]:
random_1 , random_2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193765, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193765, -1.8107855 ]], dtype=float32)>)

In [21]:
random_3 = tf.random.Generator.from_seed(42)
random_3 = random_3.normal(shape=(3,2))

random_4 = tf.random.Generator.from_seed(43)
random_4 = random_4.normal(shape=(3,2))

In [22]:
random_3 , random_4

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193765, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.23193765, -1.8107855 ],
        [ 0.09988727, -0.50998646],
        [-0.7535806 , -0.5716629 ]], dtype=float32)>)

In [23]:
not_shuffled = tf.constant([[2,3],
                            [5,6],
                            [8,2],
                            [1,0]])

tf.random.set_seed(seed=42)
tf.random.shuffle(not_shuffled,seed=42)

<tf.Tensor: shape=(4, 2), dtype=int32, numpy=
array([[5, 6],
       [8, 2],
       [2, 3],
       [1, 0]])>

In [24]:
tf.ones(shape=(3,2))
tf.zeros(shape=(3,2))

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[0., 0.],
       [0., 0.],
       [0., 0.]], dtype=float32)>

In [25]:
import numpy as np
numpy_a = np.arange(1,25,dtype=np.int32)
A = tf.constant(numpy_a,shape=(2,3,4))

In [26]:
A

<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]])>

In [27]:
rank_4_tensor = tf.zeros([2, 3, 4, 5])
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [28]:
rank_4_tensor.shape,tf.size(rank_4_tensor),rank_4_tensor.ndim

(TensorShape([2, 3, 4, 5]), <tf.Tensor: shape=(), dtype=int32, numpy=120>, 4)

In [29]:
rank_4_tensor.dtype,rank_4_tensor.ndim,rank_4_tensor.shape,rank_4_tensor.shape[0],rank_4_tensor.shape[-1],tf.size(rank_4_tensor)

(tf.float32,
 4,
 TensorShape([2, 3, 4, 5]),
 2,
 5,
 <tf.Tensor: shape=(), dtype=int32, numpy=120>)

In [30]:
rank_4_tensor[:2,:2,:2,:2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [31]:
rank_2_tensor = tf.constant([[2,3],
                             [6,7]])
rank_2_tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[2, 3],
       [6, 7]])>

In [32]:
rank_3_tensor = rank_2_tensor[...,tf.newaxis]
rank_3_tensor

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[2],
        [3]],

       [[6],
        [7]]])>

In [33]:
tf.expand_dims(rank_3_tensor,axis=-1)

<tf.Tensor: shape=(2, 2, 1, 1), dtype=int32, numpy=
array([[[[2]],

        [[3]]],


       [[[6]],

        [[7]]]])>

In [34]:
tensor = tf.constant([[10,7],
                      [3,4]])

In [35]:
tensor - 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 0, -3],
       [-7, -6]])>

In [36]:
tf.multiply(tensor,10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]])>

In [37]:
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]])>

In [38]:
tensor @ tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]])>

In [39]:

# Create (3, 2) tensor
X = tf.constant([[1, 2],
                 [3, 4],
                 [5, 6]])

# Create another (3, 2) tensor
Y = tf.constant([[7, 8],
                 [9, 10],
                 [11, 12]])
X, Y

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]])>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 7,  8],
        [ 9, 10],
        [11, 12]])>)

In [40]:
tf.reshape(X,shape=(2,3))

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]])>

In [41]:
tf.matmul(tf.reshape(X,shape=(2,3)),Y)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 58,  64],
       [139, 154]])>

In [42]:
tf.transpose(X)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 3, 5],
       [2, 4, 6]])>

In [44]:
tf.matmul(X,Y,transpose_a=True)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  98],
       [116, 128]])>

In [63]:
X,tf.transpose(Y)

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]])>,
 <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[ 7,  9, 11],
        [ 8, 10, 12]])>)

In [67]:
tf.tensordot(X,tf.transpose(Y),axes=((1),(0)))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 23,  29,  35],
       [ 53,  67,  81],
       [ 83, 105, 127]])>

In [68]:
B= tf.constant([2,3])

In [72]:
B = tf.cast(B,dtype=tf.float16)
B

<tf.Tensor: shape=(2,), dtype=float16, numpy=array([2., 3.], dtype=float16)>

In [80]:
E = tf.constant(np.random.randint(low=0,high=100,size=70),dtype=tf.float16)

In [82]:
tf.math.reduce_variance(E)

<tf.Tensor: shape=(), dtype=float16, numpy=831.0>

In [84]:
tf.argmin(E)

<tf.Tensor: shape=(), dtype=int64, numpy=62>

In [87]:
tf.one_hot([0,1,2,3],depth=2)

<tf.Tensor: shape=(4, 2), dtype=float32, numpy=
array([[1., 0.],
       [0., 1.],
       [0., 0.],
       [0., 0.]], dtype=float32)>

In [95]:
H = tf.constant(np.arange(1,10),dtype=tf.float16)
H

<tf.Tensor: shape=(9,), dtype=float16, numpy=array([1., 2., 3., 4., 5., 6., 7., 8., 9.], dtype=float16)>

In [96]:
tf.square(H)

<tf.Tensor: shape=(9,), dtype=float16, numpy=array([ 1.,  4.,  9., 16., 25., 36., 49., 64., 81.], dtype=float16)>

In [97]:
tf.sqrt(H)

<tf.Tensor: shape=(9,), dtype=float16, numpy=
array([1.   , 1.414, 1.732, 2.   , 2.236, 2.45 , 2.646, 2.828, 3.   ],
      dtype=float16)>

In [98]:

print(tf.config.list_physical_devices('GPU'))

[PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]


In [99]:
!nvidia-smi

Sun Oct  8 15:04:00 2023       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 537.34                 Driver Version: 537.34       CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                     TCC/WDDM  | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA GeForce RTX 3050 ...  WDDM  | 00000000:01:00.0  On |                  N/A |
| N/A   53C    P8               9W /  80W |   2025MiB /  4096MiB |     13%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

In [104]:
tf.constant(np.random.uniform(low=0,high=1,size=150528),shape=(224,224,3,1))

<tf.Tensor: shape=(224, 224, 3, 1), dtype=float64, numpy=
array([[[[0.88401833],
         [0.82698046],
         [0.95736148]],

        [[0.12119183],
         [0.25291235],
         [0.7135389 ]],

        [[0.56637462],
         [0.07520753],
         [0.50390864]],

        ...,

        [[0.031026  ],
         [0.58391319],
         [0.72565753]],

        [[0.70230855],
         [0.09795269],
         [0.93131631]],

        [[0.23185455],
         [0.9799064 ],
         [0.53104535]]],


       [[[0.7401734 ],
         [0.0381098 ],
         [0.39437092]],

        [[0.99584559],
         [0.03685216],
         [0.99826143]],

        [[0.03176084],
         [0.43504496],
         [0.5454544 ]],

        ...,

        [[0.60779405],
         [0.83006736],
         [0.52475244]],

        [[0.90467356],
         [0.30701889],
         [0.31596545]],

        [[0.73722202],
         [0.25800816],
         [0.46861684]]],


       [[[0.85831383],
         [0.08259724],
         [0.

In [105]:
tf.squeeze(tf.constant(np.random.uniform(low=0,high=1,size=150528),shape=(224,224,3,1)))

<tf.Tensor: shape=(224, 224, 3), dtype=float64, numpy=
array([[[0.89505617, 0.37454326, 0.99326957],
        [0.23976144, 0.98616133, 0.92056787],
        [0.84283347, 0.15900529, 0.71452421],
        ...,
        [0.40480121, 0.6919604 , 0.71195737],
        [0.81231676, 0.65939279, 0.73435746],
        [0.37076779, 0.41389867, 0.24606618]],

       [[0.96654689, 0.73362987, 0.54279313],
        [0.63862292, 0.99073325, 0.60944408],
        [0.91720155, 0.86236526, 0.68783832],
        ...,
        [0.63990639, 0.85898124, 0.24425756],
        [0.95730166, 0.51165589, 0.71880425],
        [0.80570738, 0.5237278 , 0.92315659]],

       [[0.58911641, 0.10110301, 0.21736882],
        [0.4086371 , 0.09796169, 0.86991903],
        [0.15881767, 0.11376323, 0.97395496],
        ...,
        [0.68115667, 0.99334967, 0.70830799],
        [0.44703926, 0.37097904, 0.44519163],
        [0.25525622, 0.24244816, 0.36808048]],

       ...,

       [[0.45841115, 0.84221788, 0.7292663 ],
        [0.74